name: flyway-deploy

on:
  workflow_dispatch:
  
jobs:
  flyway-Operation:
    name: "flyway-Operation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3      
      - name: run
        run: |
          gh environment GH_REPO fei-beijing/repo
          gh variable set var1 --body test
        env:
          GH_TOKEN: ${{ secrets.TOKEN}} 
