name: flyway-deploy

on:
  workflow_dispatch:
  
jobs:
  flyway-Operation:
    name: "flyway-Operation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3      
      - name: run
        run: |
          gh environment GH_REPO fei-beijing/repo
        env:
          GH_TOKEN: ${{ secrets.TOKEN}} 
      - name: add
        run: |
          gh variable set MY_VAR --body my_value
        env:
          GH_TOKEN: ${{ secrets.TOKEN}}         
