name: flyway-deploy

on:
  workflow_dispatch:
  
jobs:
  flyway-Operation:
    name: "flyway-Operation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3      
      - name: run
        run: |
          gh api -X PUT /repos/fei-beijing/repo/actions/vars \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{"test": "1"}'  
        env:
           GH_TOKEN: ${{ secrets.TOKEN}}         
